### ISSUE TITLE
Command "normalize" is not defined

### ISSUE THREAD

**Issue by spawnia** [ergebnis/composer-normalize-action#80]
#### Steps required to reproduce the problem

1. Use the first example provided in the config

#### Expected Result

* The action should run successfully

#### Actual Result

* `Command "normalize" is not defined`

See https://github.com/nuwave/lighthouse/pull/1299/checks?check_run_id=597704867

**Comment by spawnia** [comment]
Thanks @localheinz, the current `:latest` is working for me. Awaiting a release 👍

**Comment by localheinz** [comment]
@spawnia 

Apologies for the delay!

In the meantime, I archived the repository, then unarchived again and fixed the issue. Note, though, that I made some unexpected changes that might make work necessary on your end:

By default, I'm not running

```
$ composer normalize
```

with the `--dry-run` option anymore. If you need this, you now need to specify arguments and options!

**Comment by spawnia** [comment]
Do you couple that with an option to automatically commit the changes?

I have had a great time running Prettier that way, it would fit here as well.
